version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_db
    ports:
      - "3307:3306" #<local-port>:<container-port>
    volumes:
      - ./todo.sql:/docker-entrypoint-initdb.d/1.sql
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: my-todo:latest
    restart: always
    ports:
      - "8181:8080" #<local-port>:<container-port>
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/todo_db?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_THYMELEAF_CACHE: "FALSE"
#      SPRING_MESSAGES_BASENAME: i18n/messages
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
#      SPRING_JPA_HIBERNATE_DDL-AUTO: UPDATE

      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/todo_db?autoReconnect=true&failOverReadOnly=false&maxReconnects=10",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

    stdin_open: true
    tty: true

volumes:
  db: